### ISSUE TITLE
[FEATURE] Create a Docker image

### ISSUE THREAD

**Issue by timothe** [netplexflix/TV-show-status-for-Kometa#3]
Hi,

Love your project, but to implement it on my setup, I would need to containerize it.
Are you comfortable with it? Otherwise I would give it a spin and share it here.
Also it would be the opportunity to create a routine to run at 

I started a draft without tests to create a minimal image. It would be something like:

Dockerfile:
```FROM python:3.11-slim

# Disable .pyc files and enable real-time output, runs every day at 2AM by default
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    CRON="0 2 * * *"

WORKDIR /app

# Install cron and tzdata
RUN apt-get update && \
    apt-get install -y --no-install-recommends cron tzdata && \
    rm -rf /var/lib/apt/lists/*

# Copy source code
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy and set permissions for the entrypoint
COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

entrypoint.sh:
```
#!/bin/bash

# Write out the cron job using the CRON env var
echo "$CRON cd /app && python TSSK.py >> /var/log/cron.log 2>&1" > /etc/cron.d/tssk-cron

# Give execution rights on the cron job
chmod 0644 /etc/cron.d/tssk-cron

# Apply cron job
crontab /etc/cron.d/tssk-cron

# Create the log file
touch /var/log/cron.log

echo "[INFO] Starting cron with schedule: $CRON"
cron

# Tail logs to keep the container running
tail -f /var/log/cron.log
```

Instructions:

Build the image: `docker build -t tv-show-status .`

Run with: `docker run --rm -v "/my/local/config:/app/config" tv-show-status`

Or install via docker-compose:
```
version: "3.8"

services:
  tssk:
    image: tv-show-status
    container_name: tssk
    environment:
      - CRON=0 2 * * *  # every day at 2am
    volumes:
      - /my/local/config:/app/config
    restart: unless-stopped
```
